# Generated by Django 3.1.7 on 2021-03-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='avatar',
            new_name='thumbnail',
        ),
    ]
